name: CI

on:
  push:
    branches: [ main, cleaning_up ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend dependencies
        run: |
          cd backend
          npm install --silent
      - name: Install tests dependencies
        run: |
          cd tests
          npm install --silent
      - name: Lint
        run: |
          cd backend
          npm run lint
      - name: Unit & Integration Tests
        run: |
          cd tests
          npm test --passWithNoTests
      - name: Package Serverless
        run: |
          cd backend
          npx serverless package --stage dev

  # Aggregate test coverage reports if generated
  # (each project can output coverage/ in its directory)
  upload-coverage:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            frontend/coverage/
            backend/coverage/
          if-no-files-found: ignore