name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend, tests]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Type check (ts)
        run: npm run type-check --if-present
      - name: Lint
        run: npm run lint --if-present
      - name: Run tests
        run: npm test --if-present -- --runInBand --ci

  # Aggregate test coverage reports if generated
  # (each project can output coverage/ in its directory)
  upload-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            frontend/coverage/
            backend/coverage/
          if-no-files-found: ignore 